/*
 * Image file generated by img2carray.py
 * Copyright (c) 2024 Troy Schrapel
 *
 * Generated using the following command:
 *   > cd /data/gdrive/Projects/hardware/Pico/PicoVic
 *   > python3 tools/img2carray.py -i res/nyan00.png res/nyan01.png res/nyan02.png res/nyan03.png res/nyan04.png res/nyan05.png res/nyanrainbow.png res/nyanstar00.png res/nyanstar01.png res/nyanstar02.png res/nyanstar03.png res/nyanstar04.png res/nyanstar05.png -o images.c
 *
 * Timestamp: 2024-06-26 17:56:05
 *
 * Contains the following images:
 *
 * - nyan00.png
 * - nyan01.png
 * - nyan02.png
 * - nyan03.png
 * - nyan04.png
 * - nyan05.png
 * - nyanrainbow.png
 * - nyanstar00.png
 * - nyanstar01.png
 * - nyanstar02.png
 * - nyanstar03.png
 * - nyanstar04.png
 * - nyanstar05.png
 */

#ifndef __IMAGES_H
#define __IMAGES_H

#include <inttypes.h>

/* source: res/nyan00.png
 * size  : 128px x 80px
 *       : 20480 bytes
 * format: 16bpp abgr image
 */
extern uint16_t nyan00[];


/* source: res/nyan01.png
 * size  : 128px x 80px
 *       : 20480 bytes
 * format: 16bpp abgr image
 */
extern uint16_t nyan01[];


/* source: res/nyan02.png
 * size  : 128px x 80px
 *       : 20480 bytes
 * format: 16bpp abgr image
 */
extern uint16_t nyan02[];


/* source: res/nyan03.png
 * size  : 128px x 80px
 *       : 20480 bytes
 * format: 16bpp abgr image
 */
extern uint16_t nyan03[];


/* source: res/nyan04.png
 * size  : 128px x 80px
 *       : 20480 bytes
 * format: 16bpp abgr image
 */
extern uint16_t nyan04[];


/* source: res/nyan05.png
 * size  : 128px x 80px
 *       : 20480 bytes
 * format: 16bpp abgr image
 */
extern uint16_t nyan05[];


/* source: res/nyanrainbow.png
 * size  : 34px x 60px
 *       : 4080 bytes
 * format: 16bpp abgr image
 */
extern uint16_t nyanrainbow[];


/* source: res/nyanstar00.png
 * size  : 21px x 21px
 *       : 882 bytes
 * format: 16bpp abgr image
 */
extern uint16_t nyanstar00[];


/* source: res/nyanstar01.png
 * size  : 21px x 21px
 *       : 882 bytes
 * format: 16bpp abgr image
 */
extern uint16_t nyanstar01[];


/* source: res/nyanstar02.png
 * size  : 21px x 21px
 *       : 882 bytes
 * format: 16bpp abgr image
 */
extern uint16_t nyanstar02[];


/* source: res/nyanstar03.png
 * size  : 21px x 21px
 *       : 882 bytes
 * format: 16bpp abgr image
 */
extern uint16_t nyanstar03[];


/* source: res/nyanstar04.png
 * size  : 21px x 21px
 *       : 882 bytes
 * format: 16bpp abgr image
 */
extern uint16_t nyanstar04[];


/* source: res/nyanstar05.png
 * size  : 21px x 21px
 *       : 882 bytes
 * format: 16bpp abgr image
 */
extern uint16_t nyanstar05[];

#endif